### ISSUE TITLE
Why wrap the build method in a Container?

### ISSUE THREAD

**Issue by erf** [ufrshubham/multi-value-listenable-builder#2]
Why wrap the build method in a Container?

It is a costly Widget, can't you just return a `ValueListenableBuilder` ?

**Comment by ufrshubham** [comment]
Oh! I remember I was trying something out and probably forgot to remove the `Container` before publishing the package. Nice catch, I remove it in next version.

**Comment by ufrshubham** [comment]
Fixed via 38d376c79412ea5f5b3dc27d98ed2709ea3d2e52
