### ISSUE TITLE
Alternative to recursive ValueListenableBuilder ?

### ISSUE THREAD

**Issue by erf** [ufrshubham/multi-value-listenable-builder#3]
Calling `ValueListenableBuilder` recursively seem costly .. could you not instead use `AnimatedBuilder` and just return all the values each time one value changed?

**Comment by ufrshubham** [comment]
@erf I am not sure if I understand the issue here, or how using `AnimatedBuilder` will fix it either. If possible can you show some example comparing current recursive VLB and your proposed solution?

Although the `VLB`s are nested, it does not necessarily mean that `builder` of all the `VLB`s will get executed every time. I would really appreciate if you can provide some data or a use case to show how where current approach is causing performance issue.

**Comment by erf** [comment]
@ufrshubham not really sure it is an actual issue (have not performed a benchmark), i just saw from the original [stackoverflow issue](https://stackoverflow.com/questions/58030337/valuelistenablebuilder-listen-to-more-than-one-value) (where you posted a link to this), that you could use `AnimatedBuilder` to listen to multiple `ValueNotifier` objects using `Listenable.merge` as it accepts a `Listenable` object. I have not looked much into that code yet of [AnimatedBuilder](https://github.com/flutter/flutter/blob/fd9ce277482c906a2324066c4107779536d6edfe/packages/flutter/lib/src/widgets/transitions.dart). But i think you could copy take the same approach as `AnimatedBuilder` / `AnimatedWidget`, but just return the state of all `ValueNotifier` values, each time the `Listenable` object changes.

**Comment by erf** [comment]
I made a new [issue](https://github.com/flutter/flutter/issues/93124) in the Flutter repo regarding this.

**Comment by erf** [comment]
I made a new PR, with some few refactorings now. Sorry i forgot to put it in a separate branch, is that ok?

I also made a new [branch](https://github.com/erf/multi-value-listenable-builder/tree/animated-builder), where i replaced the recursive `ValueListenableBuilder` with using `AnimatedBuilder`. What do you think?

The code is simpler and seem to work as expected, but should be benchmarked..

**Comment by ufrshubham** [comment]
Yes, it is fine (it is anyways a very small package 😅).

I looked at your AnimatedBuilder approach too. It definitely is more compact and easy to understand. You can go ahead and create a PR for it as well.

**Comment by ufrshubham** [comment]
Thanks for fixing this @erf !

**Comment by erf** [comment]
No problem :) Will you push a new release to pub.dev at some point ?

**Comment by ufrshubham** [comment]
I just pushed 0.0.2 to pub. Probably will take some time to become public.
