### ISSUE TITLE
Suggestion: Add unit tests

### ISSUE THREAD

**Issue by erf** [ufrshubham/multi-value-listenable-builder#8]
I suggest adding a few unit tests, to make sure this works properly.

**Comment by ufrshubham** [comment]
Good idea. Let me know if you are interested in taking up this as well. 😄

**Comment by erf** [comment]
Added a PR ;)

**Comment by erf** [comment]
I'm not very familiar with these tests, but we should optimally not do a manual pump, but instead detect that the `MultiValueListenableBuilder.builder` is called when the `listenables` is changed, i think .. but no idea how to do that.

**Comment by erf** [comment]
I'll just close it for now and we can open a new issue later if needed.
